### ISSUE TITLE
Error after starting jupyter notebook

### ISSUE THREAD

**Issue by Sooyka** [fricas/jfricas#3]
After installing and starting as stated in instruction there was the following message:
```
While evaluating the form starting at line 16, column 0
  of  
   >> System error:
   Don't know how to REQUIRE ASDF.
See also:
  The SBCL Manual, Variable SB-EXT:*MODULE-PROVIDER-FUNCTIONS*
  The SBCL Manual, Function REQUIRE

 
   >> System error:
   Package WEBSPAD does not exist.

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from " (defvar...">
```
and jupyter notebook was unusable -- after providing an intput it frosed with In[*]

**Comment by MrBlueXav** [comment]
Exactly the same error here !

**Comment by hemmecke** [comment]
nilqed just notified me that it is a problem connected to the installation of Lisp. We will look into it soon.

**Comment by hemmecke** [comment]
See https://groups.google.com/g/fricas-devel/c/YAAYt57bwuQ
